<?php
    return [
        "policies"=>[   'SOAT' => 'Seguro Obligatorio de Accidentes de Tránsito',
                            'AFOCAT' => 'Asociaciones de Fondos Regionales o Provinciales contra Accidentes de Tránsito',
                        ],
        "vehicleServiceTypes"=>[   '0' => 'Particular',
                            '1' => 'Transporte Regular de Personas',
                            '2' => 'Transporte Privado de Personas',
                            '3' => 'Transporte Especial de Personas – Turístico',
                            '4' => 'Transporte Especial de Personas –Trabajadores',
                            '5' => 'Transporte Especial de Personas –Estudiantes',
                            '6' => 'Transporte Especial de Personas –Social',
                            '7' => 'Transporte Especial de Personas –Auto Colectivo',
                            '8' => 'Transporte Especial de Personas –Taxi',
                            '9' => 'Transporte de Mercancías en General Público',
                            '10' => 'Transporte de Mercancías Privado', 
                            '11' => 'Transporte de Materiales y Residuos Peligrosos',
                            '12' => 'Servicio Especial Comunal de Transporte de Pasajeros por Carretera',
                            '13' => 'Servicio de Transporte Publico Especial de Pasajeros de Pasajeros en Vehículos Menores',
                            '14' => 'Servicio de Transporte Mixto',
                            '15' => 'Servicio de Transporte Internacional de Mercancías por Carretera de la Comunidad Andina',
                            '16' => 'Servicio de Transporte de Pasajeros por Carretera entre Tacna – Arica',
                            '17' => 'Servicio de Transporte Transfronterizo de Pasajeros en Ómnibus Entre Perú – Ecuador',
                            '18' => 'Servicio de Transporte Transfronterizo de Pasajeros en Taxi Entre Perú – Ecuador',
                            '19' => 'Servicio de Transporte Transfronterizo Turístico entre Perú – Ecuador',
                            '20' => 'Servicio de Transporte Transfronterizo de Mercancías entre Perú – Ecuador',
                            '21' => 'Servicio de Transporte Internacional Terrestre de Pasajeros por Carretera - ATIT (Cono Sur)',
                            '22 de Transporte Internacional Terrestre de Mercancías por Carretera - ATIT (Cono Sur)',
                    ],
        "vehicleServiceAreas" =>[
                                '0' => 'Ninguno',
                                '1' => 'Ámbito Nacional',
                                '2' => 'Ámbito Regional',
                                '3' => 'Ámbito Provincial',
                                '4' => 'Ámbito Internacional(Pasajeros)',
                                '5' => 'Ámbito Distrital',
                            ],
        "cancellations"=>[
                                    '0' => 'Error digitación u Omisión',
                                    '1' => 'Error de impresión de documento',
                                    '2' => 'Error de Operación',
                                    '3' => 'Pérdida o Robo',
                                    '4' => 'Deterioro', 
                                ],
        "inspectionTypes"=>[  
                                    '1' => 'Ordinaria',
                                    '2' => 'Ordinaria y Complementaria',
                                    '3' => 'Extraordinaria',
                                    '4' => 'Incorporación',
                                    '5' => 'Complementaria',
                                ], 
        "vehicleCategories"=>[  
                                        '1' => 'M1',
                                        '2' => 'M2',
                                        '3' => 'M3',
                                        '4' => 'N1', 
                                        '5' => 'N2',
                                        '6' => 'N3',
                                        '7' => 'O1',
                                        '8' => 'O2',
                                        '9' => 'O3',
                                        '10' => 'O4',
                                        '11' => 'L1',
                                        '12' => 'L2',
                                        '13' => 'L3',
                                        '14' => 'L4',
                                        '15' => 'L5'
                        ],
            "insurers"=>[
                            '1' => 'INTERSEGURO SOAT',
                            '2' => 'RIMAC SEGUROS SOAT',
                            '3' => 'LA POSITIVA SOAT',
                            '4' => 'MAPFRE PERU SOAT',
                            '5' => 'PACIFICO SEGUROS SOAT',
                            '6' => 'HDI SEGUROS S.A. SOAT',
                            '7' => 'SEGUROS SURA SOAT',
                            '8' => 'PROTECTA SOAT',
                            '9' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO CHIMBOTE REGION ANCASH "AFOCAT CHIMBOTE REGION ANCASH" AFOCAT',
                            '10' => 'ASOCIACION FONDO REGIONAL CONTRA ACCIDENTES DE TRANSITO DE ANCASH "AFORCAT - ANCASH" AFOCAT  ',
                            '11' => 'ASOCIACIÓN FONDO CONTRA ACCIDENTES DE TRÁNSITO LA ÚNICA "AFOCAT LA ÚNICA" AFOCAT',
                            '12' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO DE LA REGION AREQUIPA "AFOCAT - REGION AREQUIPA" AFOCAT',
                            '13' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO DEL FRENTE UNICO DE TRANSPORTE PUBLICO URBANO E INTERURBANO DE LA REGION AREQUIPA "AFOCAT FUTUIRA" AFOCAT',
                            '14' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO DE LA REGION AREQUIPA Y ANEXOS "AFOCAT RAVISUR" AFOCAT ',
                            '15' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO DE LA REGION DE CAJAMARCA "AFOCAT - REGION CAJAMARCA" AFOCAT 16',
                            '16' => 'ASOCIACIÓN FONDO DE COBERTURAS DE ACCIDENTES DE TRÁNSITO DEL CUMBE "AFOCATDC" AFOCAT',
                            '17' => 'ASOCIACION DE FONDOS CONTRA ACCIDENTES DE TRANSITO REGION CUSCO "AFOCAT REGION CUSCO" AFOCAT',
                            '18' => 'ASOCIACIÓN FONDO CONTRA ACCIDENTES DE TRÁNSITO LA SOLUCIÓN DEL CUSCO "AFOCAT LA SOLUCIÓN CUSCO" AFOCAT',
                            '19' => 'ASOCIACIÓN DE FONDOS CONTRA ACCIDENTES DE TRÁNSITO REGIONAL BELLA DURMIENTE - "AFOCAT REGIONAL BELLA DURMIENTE" "AFOCAT REGIONAL BELLA DURMIENTE" AFOCAT',
                            '20' => 'ASOCIACIÓN FONDO CONTRA ACCIDENTES DE TRÁNSITO REGIONAL LEON DE HUÁNUCO "AFOCAT LEÓN DE HUÁNUCO" AFOCAT',
                            '21' => 'ASOCIACION DE FONDOS CONTRA ACCIDENTES DE TRANSITO REGION ICA "AFOCAT REGION ICA" AFOCAT',
                            '22' => 'ASOCIACIÓN DE FONDO CONTRA ACCIDENTES DE TRÁNSITO EL ANGEL "AFOCAT EL ANGEL" AFOCAT',
                            '23' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO DE LA REGION JUNIN "AFOCAT - JUNIN" AFOCAT',
                            '24' => 'ASOCIACIÓN DE FONDOS CONTRA ACCIDENTES DE TRÁNSITO UNION "AFOCATU" AFOCAT',
                            '25' => 'ASOCIACIÓN DE FONDO CONTRA ACCIDENTES DE TRÁNSITO DE LOS TRANSPORTISTAS DE LA REGIÓN JUNÍN PASCO HUÁNUCO "AFOCAT R.J.P.H." AFOCAT',
                            '26' => 'ASOCIACIÓN FONDO CONTRA ACCIDENTES DE TRÁNSITO MACRO - REGIÓN CENTRO NOR-ORIENTE "AFOCAT - CENTRO NOR - ORIENTE" AFOCAT',

                            '27' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO DE LA REGION LA LIBERTAD "AFOCAT - TRUJILLO REGION LA LIBERTAD" AFOCAT',
                            '28' => 'ASOCIACION FONDO DE COBERTURA DE ACCIDENTES DE TRANSITO - LA LIBERTAD "AFOCAT LA LIBERTAD" AFOCAT',
                            '29' => 'ASOCIACION FONDO REGIONAL CONTRA ACCIDENTES DE TRANSITO NUEVO HORIZONTE REGION LA LIBERTAD "AFOCAT NUEVO HORIZONTE REGION LA LIBERTAD" AFOCAT',
                            '30' => 'ASOCIACION DE USUARIOS DEL FONDO REGIONAL CONTRA ACCIDENTES DE TRANSITO - FORCAT "FORCAT" AFOCAT',
                            '31' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO LÍDER PERÚ "AFOCAT LÍDER PERÚ" AFOCAT',
                            '32' => 'AUTOSEGUROS DE FONDOS CONTRA ACCIDENTES DE TRANSITO DE LIMA "AUTOSEGUROS AFOCAT LIMA" AFOCAT',
                            '33' => 'AUTOSEGURO ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO "AUTOSEGURO AFOCAT" AFOCAT',
                            '34' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO LIMA METROPOLITANA "AFOCAT LIMA METROPOLITANA" AFOCAT',

                            '35' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO DE LA REGION LIMA METROPOLITANA Y PROVINCIA CONSTITUCIONAL DEL CALLAO "AFOCAT - REGION LIMA" AFOCAT',
                            '36' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO PREMIUM "AFOCAT PREMIUM" AFOCAT',
                            '37' => 'ASOCIACION DE FONDOS CONTRA ACCIDENTES DE TRANSITO SOCAT PERU "AFOCAT SOCAT PERU" AFOCAT',
                            '38' => 'ASOCIACION DE FONDOS CONTRA ACCIDENTES DE TRANSITO (AFOCAT) NUESTRA SEÑORA DE LA ASUNCION "NUESTRA SEÑORA DE LA ASUNCION" AFOCATsdf',
                            '39' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO DE LA REGION LIMA PROVINCIAS "AFOCAT LIMA PROVINCIAS" AFOCAT',

                            '40' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO DEL ORIENTEREGION LORETO "AFOCAT DEL ORIENTE - REGION LORETO "AFOCAT DEL ORIENTE - REGION LORETO" AFOCAT',
                            '41' => 'ASOCIACIÓN DE FONDOS CONTRA ACCIDENTES DE TRÁNSITO DE LA REGIÓN MOQUEGUA "AFOCAT MOQUEGUA" AFOCAT',
                            '42' => 'ASOCIACION DEL FONDO CONTRA ACCIDENTES DE TRANSITO - AFOCAT TRANS REGION PIURA "AFOCAT TRANS REGION PIURA" AFOCAT',
                            '43' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO - PIURA "AFOCAT - PIURA" AFOCAT',
                            '44' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO LA PRIMERA "AFOCAT LA PRIMERA" AFOCAT',
                            '45' => 'FONDO CONTRA ACCIDENTES DE TRÁNSITO REGIÓN PUNO "FONCAT" AFOCAT',
                            '46' => 'ASOCIACION FONDO CONTRA ACIIDENTES DE TRANSITO DE PUNO "AFOCAT PUNO" AFOCAT',

                            '47' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO DE LA REGION SAN MARTIN "AFOCAT REGION SAN MARTIN" AFOCAT',
                            '48' => 'ASOCIACIÓN DE FONDOS CONTRA ACCIDENTES DE TRÁNSITO AFOCAT - AFOSECAT - SAN MARTÍN "AFOCAT - AFOSECAT - SAN MARTÍN" AFOCAT',

                            '49' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO SUR PERÚ REGIÓN TACNA "AFOCAT SUR PERÚ REGIÓN TACNA" AFOCAT',
                            '50' => 'ASOCIACIÓN FONDO CONTRA ACCIDENTES DE TRÁNSITO REGION TACNA "AFOCAT REGION TACNA" AFOCAT',

                            '51' => 'FONDO DE ASISTENCIA SOCIAL DE LOS MOTOTAXISTAS Y TRANSPORTISTAS DE TUMBES "FASMOT" AFOCAT',
                            '52' => 'ASOCIACION FONDO CONTRA ACCIDENTES DE TRANSITO REGIONAL UCAYALINO "AFOCAT UCAYALINO REGIÓN UCAYALI" AFOCAT',
                            '53' => 'BNP PARIBAS CARDIF SOAT',
                
                            '54' => 'CRECER SEGUROS S. A. SOAT',
                            '55' => 'INSUR SOAT', 
                            '56' => 'CHUBB PERU SOAT',
                            '57' => 'RIGEL PERU SOAT',
                            
                            '58' => 'VIDA CAMARA SOAT',
                            '59' => 'OHIO NATIONAL VIDA SOAT', 
                            '60' => 'COFACE SOAT',
                            '61' => 'AVLA PERU SOAT',
                            '62' => 'LIBERTY SEGUROS SOAT',
                            '63' => 'SECRX',
                            
                        ],
        "responses"=>[
                '1' => 'MSJ01 Código de entidad no existe o no es correcto',
                '2' => 'MSJ02 Código de local no existe o no es correcto','3' => 'MSJ03 Código identificador de validación está vacío o no existe o no es correcto.',
                '4' => 'MSJ04 La autorización del CITV se encuentra vencida, por favor coordine con el MTC (Fecha de vencimiento)',
                '5' => 'MSJ05 El CITV se encuentra sancionado.',
                '6' => 'MSJ06 El CITV tiene registrado el día de hoy como permiso de no operación.',
                '7' => 'MSJ07 EL día de hoy no se encuentra autorizado para operar.',
                '8' => 'MSJ08 No se encuentra autorizado para operar en este horario.',
                '9' => 'MSJ09 No se cuenta con el código de inicio de operación diaria.',
                '10' => 'MSJ10 El vehículo de placa ABC123 no existe en el registro vehicular',
                '11' => 'MSJ11 Tiene que enviar el tipo de póliza y el número de póliza, no se puede continuar con el proceso',
                '12' => 'MSJ12 La revisión no cuenta con el estado de aprobación o desaprobación 13 MSJ13 Error de proceso, intente de nuevo si persiste el error coordine con el MTC.',
                '14' => 'MSJ14 El tipo de servicio no existe.',
                '15' => 'MSJ15 El tipo de ámbito no existe.',
                '16' => 'MSJ16 El tipo de inspección no existe.',
                '17' => 'MSJ17 Código de inicio de operaciones diaria vacío. DGTT - OTI 9 ',
                '18' => 'MSJ18 Número de matrícula del vehículo vacío o no es correcto',
                '19' => 'MSJ19 Código del tipo de póliza vacío',
                '20' => 'MSJ20 Número de póliza vacío',
                '21' => 'MSJ21 Fecha de inicio de vigencia de póliza no debe ser mayor a la actual.',
                '22' => 'MSJ22 Fecha de inicio de vigencia de póliza vacío o formato incorrecto',
                '23' => 'MSJ23 Fecha de fin de vigencia de póliza vacío o formato incorrecto',
                '24' => 'MSJ24 Tipo de servicio vacío o no es correcto',
                '25' => 'MSJ25 Tipo de ámbito vacío o no es correcto',
                '26' => 'MSJ26 Tipo de inspección técnica vacío o no es correcto',
                '27' => 'MSJ27 El código de observación de la revisión técnica no existe o está vacío.',
                '28' => 'MSJ28 El número de ficha vacío',
                '29' => '<MSJ29 La fecha inicio del certificado vacío',
                '30' => 'MSJ30 La fecha final del certificado vacío',
                '31' => 'MSJ31 La fecha final no puede ser igual o menor la fecha inicial del certificado',
                '32' => 'MSJ32 La fecha inicio del certificado no puede ser diferente a la fecha actual',
                '33' => 'MSJ33 El código de categoría no existe o está vacío.',
                '34' => 'MSJ34 El tipo de póliza no existe.',
                '35' => 'MSJ35 La fecha final de la póliza no debe ser menor que la fecha inicio de la póliza.',
                '36' => 'MSJ36 El periodo de vigencia de la póliza debe ser de 1 año',
                '37' => 'MSJ37 La fecha final de la póliza no debe ser menor a la actual',
                '38' => 'MSJ38 El Código de inicio de operación diaria, el número de ficha y/o placa vehicular no son correctos.',
                '39' => 'MSJ39 El código de inicio de operación, placa y certificado no son compatibles.',
                '40' => 'MSJ40 El número de certificado pertenece a un informe.',
                '41' => 'MSJ41 El número de certificado está vacío.',
                '42' => 'MSJ42 El motivo de anulación no es correcto o está vacío.',
                '43' => 'MSJ43 El certificado ya se encuentra anulado.',
                '44' => 'MSJ44 El número de ficha ya ha sido utilizada.',
                '45' => 'MSJ45 La placa no tiene póliza.',
                '46' => 'MSJ46 La póliza esta vencida',
                '47' => 'MSJ47 El número de póliza ya existe, pertenece a otra placa',
                '48' => 'MSJ48 Tiene una póliza vigente.',
                '49' => 'MSJ49 El número de certificado no existe.',
                '50' => 'MSJ50 El tipo de ámbito, tipo de servicio y tipo de inspección no son compatibles con la categoría del vehículo.',
                '51' => 'MSJ51 La categoría del vehículo no está autorizada para el registro de la póliza.',
                '52' => 'MSJ52 El tipo de póliza no es compatible con la categoría del vehículo.',
                '53' => 'MSJ53 El formato de placa del vehículo no es correcto.',
                '54' => 'MSJ54 Código de la aseguradora está vacío o no existe o no es correcto.',
                '55' => 'MSJ55 La póliza a actualizar no se encuentra registrada.',
                '56' => 'MSJ56 El tipo de póliza no es compatible con la empresa aseguradora.',
                '57' => 'MSJ57 Los datos de acceso al servicio son incorrectos.',
                '58' => 'MSJ58 No ha trascurrido el tiempo mínimo de 5 minutos para la emisión del certificado o informe.',
                '59' => 'MSJ59 La autorización de la empresa de CITV se encuentra inhabilitada ',
                '60' => 'MSJ60 La autorización de la empresa de CITV se encuentra suspendida',
                '61' => 'MSJ61 La autorización de la empresa de CITV se encuentra cancelada',
                '62' => 'MSJ62 La autorización de la empresa de CITV se encuentra improcedente',
                '66' => 'MSJ63 La autorización de la empresa de CITV se encuentra anulada',
                '4' => 'MSJ64 La autorización de la empresa de CITV se encuentra vencida',
                '65' => 'MSJ65 La autorización de la empresa de CITV se encuentra caduca',
                '66' => 'MSJ66 La autorización de la empresa de CITV se encuentra dada de baja',
                '67' => 'MSJ67 La autorización del local de CITV se encuentra inhabilitado',
                '68' => 'MSJ68 La autorización del local de CITV se encuentra suspendida',
                '69' => 'MSJ69 La autorización del local de CITV se encuentra cancelada',
                '70' => 'MSJ70 La autorización del local de CITV se encuentra improcedente',
                '71' => 'MSJ71 La autorización del local de CITV se encuentra anulada',
                '72' => 'MSJ72 La autorización del local de CITV se encuentra vencida',
                '73' => 'MSJ73 La autorización del local de CITV se encuentra caduca',
                '74' => 'MSJ74 La autorización del local de CITV se encuentra dada de baja',
                '75' => 'MSJ75 No cuenta con inicio de operación registrado.',
                '76' => 'MSJ76 El campo solicitud de nuevo certificado no existe o está vacío.',
                '77' => 'MSJ77 El certificado pertenece a otra placa.',
                '78' => 'MSJ78 El certificado fue emitido por otro CITV.',
            ]
        ];